### ISSUE TITLE
能够正常登录，但是主界面无法显示

### ISSUE THREAD

**Issue by KoJail** [Kuriputon/Item-Revive#1]
![屏幕截图 2024-10-23 075818](https://github.com/user-attachments/assets/1d99ec69-f123-4058-8ef1-91263b3d68da)
如图，登录进去后主界面没有加载出来
![屏幕截图 2024-10-23 075831](https://github.com/user-attachments/assets/ca04d7fc-0100-4cab-a299-cb13a17ce928)
具体报错如上

**Comment by Kuriputon** [comment]
> ![屏幕截图 2024-10-23 075818](https://private-user-images.githubusercontent.com/137483051/379051687-1d99ec69-f123-4058-8ef1-91263b3d68da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODc1MDUsIm5iZiI6MTczNDY4NzIwNSwicGF0aCI6Ii8xMzc0ODMwNTEvMzc5MDUxNjg3LTFkOTllYzY5LWYxMjMtNDA1OC04ZWYxLTkxMjYzYjNkNjhkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwOTMzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTBlM2FkODNiYTU2OWJhOTAxMjgzYTM5OWM0Njc1YmRmMmExZjA3MjkzZmFjMTZjY2Y4YTYxMWJjNDM4MTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lfWjAKfx_cuOjPDPvbc-gbUcPPt2bIUI5GpBvmugb8I) 如图，登录进去后主界面没有加载出来 ![屏幕截图 2024-10-23 075831](https://private-user-images.githubusercontent.com/137483051/379051766-ca04d7fc-0100-4cab-a299-cb13a17ce928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2ODc1MDUsIm5iZiI6MTczNDY4NzIwNSwicGF0aCI6Ii8xMzc0ODMwNTEvMzc5MDUxNzY2LWNhMDRkN2ZjLTAxMDAtNGNhYi1hMjk5LWNiMTNhMTdjZTkyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQwOTMzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjNjZjdjODcyYmE1NzU1MTk0MGY5Y2QwNzVjNTRjYWE0M2U5MjBmODIzNGVjYzM3NmExNmRkZDM4NjkyMDU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JgPyu9QHqisf7i_pnG6fwMqi4mvx0tcC93W0iSSZGZs) 具体报错如上

Hi KoJail,

I hope you're doing well! I’ve made some improvements to the project based on the issue you raised earlier.

Thanks again for your feedback.
