### ISSUE TITLE
Cannot view item detail right after adding it

### ISSUE THREAD

**Issue by untrueFire** [Kuriputon/Item-Revive#2]
Full error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "<python path>\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "<project path>\Item-Revive\utilities.py", line 116, in <lambda>
    image_label.bind("<Button-1>", lambda e: show_frame(frames, detail_frame_name))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<project path>\Item-Revive\utilities.py", line 177, in show_frame
    frame = frames[frame_name]
            ~~~~~~^^^^^^^^^^^^
KeyError: 'detail_frame_27'
```
## How to reproduce
- Add an item, with or without image
- select it in `plaza` or `available_page` or `want_page` according to its type
- The page becomes empty, with the above error message in console
## What do you except?
- The page showing the item's information
## What happened instead?
- The page became blank, showing nothing
## Environment information
```cmd
>ver

Microsoft Windows [版本 10.0.22631.4391]

> python --version
Python 3.11.5

>python -m pip list
Package    Version
---------- -------
pillow     11.0.0
pip        24.3
pyglet     2.0.18
setuptools 65.5.0
```

## P.S.
The item became viewable after restarting the application

**Comment by Kuriputon** [comment]
> Full e

> Full error:
> 
> ```
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "<python path>\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
>     return self.func(*args)
>            ^^^^^^^^^^^^^^^^
>   File "<project path>\Item-Revive\utilities.py", line 116, in <lambda>
>     image_label.bind("<Button-1>", lambda e: show_frame(frames, detail_frame_name))
>                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<project path>\Item-Revive\utilities.py", line 177, in show_frame
>     frame = frames[frame_name]
>             ~~~~~~^^^^^^^^^^^^
> KeyError: 'detail_frame_27'
> ```
> 
> ## How to reproduce
> * Add an item, with or without image
> * select it in `plaza` or `available_page` or `want_page` according to its type
> * The page becomes empty, with the above error message in console
> 
> ## What do you except?
> * The page showing the item's information
> 
> ## What happened instead?
> * The page became blank, showing nothing
> 
> ## Environment information
> ```batchfile
> >ver
> 
> Microsoft Windows [版本 10.0.22631.4391]
> 
> > python --version
> Python 3.11.5
> 
> >python -m pip list
> Package    Version
> ---------- -------
> pillow     11.0.0
> pip        24.3
> pyglet     2.0.18
> setuptools 65.5.0
> ```
> 
> ## P.S.
> The item became viewable after restarting the application

Hi untrueFire,

I hope you're doing well! I’ve made some improvements to the project based on the issue you raised earlier. 

Thanks again for your feedback.
